[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "img-src 'self' data: https://firebasestorage.googleapis.com https://trello.com https://*.trello.com;"
